import Head from 'next/head'
import { PostCard, Categories, PostWidget } from '../components'


const posts = [
  {title: 'React Testing', exerpt: 'Learn React Testing'},
  {title: 'React with Tailwind', exerpt: 'Learn React With Tailwind'}

]

export default function Home() {
  return (
    <div className="container mx-auto px-10 mb-8">
      <Head>
        <title>Unscripted - Personal Blog Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
      
      <div>
        {posts.map((post, index) => (
          <PostCard post={post} key={post.title}/>
          ))}
      </div>
        <div className="lg:col-span-4 col-span-1">
          <div className='lg:sticky relative top-8'>
            <PostWidget />
            <Categories />
          </div>
        </div>
      </div>

    </div>
  )
}
